### ISSUE TITLE
F13 - tradução do tema da iniciativa

### ISSUE THREAD

**Issue by ricardoas** [nazareno/diferentonas-server#1]
Como cidadão, ao escolher uma cidade, eu visualizo as diferentices de uma cidade catalogadas segundo a função referente à iniciativa, para que assim possa entender melhor a relação entre as diferentices e meu dia a dia.

**Comment by nazareno** [comment]
Já temos um script para baixar todos os dados de transferências do SIAFI na sua máquina. Problema: são 3 GB.

**Comment by nazareno** [comment]
Na verdade não precisamos dos 3GB :)
Scripts e código java atualizados para usar a função orçamentária associada à transferência como tema. Ficou bem melhor.
