### ISSUE TITLE
Novidades de comentários novos ficam sumindo ao adicionar novos comentários

### ISSUE THREAD

**Issue by luizaugustomm** [nazareno/diferentonas-server#17]
Quando eu adiciono novos comentários a uma iniciativa que eu sigo, eles aparecem na chamada de novidades de comentários. No entanto, o máximo de objetos que aparecem lá é 10. Se eu adicionar um novo comentário, o mais antigo some.

**Comment by ricardoas** [comment]
Esse é o comportamento esperado pra uma paginação, né? Ou eu entendi
errado...

**Comment by luizaugustomm** [comment]
É verdade. 😅

**Comment by ricardoas** [comment]
Então vou fechar...
