### ISSUE TITLE
Atualização decentralizada e tolerante a falhas

### ISSUE THREAD

**Issue by nazareno** [nazareno/diferentonas-server#19]
Implementar o job de atualização de dados (obtenção do SICONV/SIAFI e inserção no BD) como um trabalho decentralizado dos nós que têm servidores web rodando. 

Pra isso, cada nó web deve escolher um horário de atualização. Nesse horário, ele vê se o dado do dia atual já foi colocado no BD. Se não foi, ele coloca e marca isso no BD.

**Comment by nazareno** [comment]
Resolvido, com eleição líder, por nosso líder para assuntos de consenso distribuído, @ricardoas .

**Comment by ricardoas** [comment]
Nunca achei que eu seria capaz... ;p
