### ISSUE TITLE
F14 - termos mais comuns

### ISSUE THREAD

**Issue by ricardoas** [nazareno/diferentonas-server#2]
Como cidadão, ao navegar no sistema, vejo os termos técnicos (eg. convênio, transferência, etc.) substituídos por palavras mais comuns, para que assim a interface me seja mais inteligível.

**Comment by nazareno** [comment]
Refatoramos todos os termos nas variáveis de acordo com essa planilha aqui: https://docs.google.com/spreadsheets/d/13t7tjuovJB1qNcvjR3NMUyduS20aHE7GqioxkYlOEJw/edit#gid=0
