### ISSUE TITLE
Warnings em consolida_siafi.R siafi/*csv

### ISSUE THREAD

**Issue by nazareno** [nazareno/diferentonas-server#20]
Ao executar via RScript com muitos arquivos, vemos alguns Warning: unknown column: Número Convênio. Porém não consegui reproduzir no RStudio, e não consigo ver nenhum efeito colateral. Mas é uma boa se livrar das warnings.

**Comment by ricardoas** [comment]
@nazareno será que era aquela coluna extra de ontem????????

**Comment by nazareno** [comment]
Nem vejo mais a warning, pra falar a verdade...

**Comment by ricardoas** [comment]
Então vou fechar... :)
